package com.japansport.dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * DAO base class - cung cấp các helper dùng chung cho tất cả DAO:
 * - getConnection(): lấy Connection từ DBConnect
 * - getStatement(): tạo Statement thường (dùng cho query đơn giản)
 * - getPreparedStatement(): tạo PreparedStatement an toàn (tránh SQL injection)
 */
public abstract class DAO {

    /**
     * Lấy Connection từ DBConnect.
     * Nếu không lấy được sẽ throw SQLException để DAO con tự xử lý.
     */
    protected Connection getConnection() throws SQLException {
        Connection conn = DBConnect.getInstance().getConnect();
        if (conn == null) {
            throw new SQLException("Cannot get database connection");
        }
        return conn;
    }

    /**
     * Tạo Statement thường – giữ lại cho các DAO cũ đang dùng.
     * Không throw checked exception để không làm hỏng code cũ.
     */
    protected Statement getStatement() {
        try {
            return getConnection().createStatement();
        } catch (SQLException e) {
            e.printStackTrace();
            return null;
        }
    }

    /**
     * Helper tạo PreparedStatement (dùng trong DAO mới).
     */
    protected PreparedStatement getPreparedStatement(String sql) throws SQLException {
        return getConnection().prepareStatement(sql);
    }

    /**
     * Helper tạo PreparedStatement với cờ RETURN_GENERATED_KEYS.
     */
    protected PreparedStatement getPreparedStatement(String sql, int autoGeneratedKeys) throws SQLException {
        return getConnection().prepareStatement(sql, autoGeneratedKeys);
    }
}
